[tools]
node = "25"

[settings]
experimental = true

[hooks]
enter = """
mise run install
"""

[tasks.install]
description = "Install project dependencies"
run = "npm install"

[tasks.build]
description = "Build the distributable files"
depends = ["install"]
run = "npm run build"
